# Generated by Django 5.1.6 on 2025-02-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinksession',
            name='session_id',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
